const pngBase = name => `https://s3-ap-northeast-1.amazonaws.com/xiaojibucket/web/${name}.png`;

const pngBaseV2 = name => `https://xiangx-1253949149.cossh.myqcloud.com/XiangX-App/website/v2/images/${name}.png`;

export const Image = {
    BannerBG: pngBase('banner_image'),
    Logo: pngBase('logo'),
    GooglePlayBanner: pngBaseV2('android_download_button_click@2x'),
    AppStoreBanner: pngBaseV2('iphone_download_click_or_hover_button@2x'),
    AppleQRCode: pngBaseV2('code_image@2x'),
    AndroidQRCode: pngBaseV2('androidv1_qrcode'),
    Intro1: pngBaseV2('pic_01_image@2x'),
    Intro2: pngBaseV2('pic_02_image@2x'),
    Intro3: pngBaseV2('pic_03_image@2x'),
    Category1: pngBaseV2('bag_image@2x'),
    Category2: pngBaseV2('access_image@2x'),
    Category3: pngBaseV2('jewel_image@2x'),
    Category4: pngBaseV2('watch_image@2x'),
    Brand1: pngBaseV2('chanel_image@2x'),
    Brand2: pngBaseV2('prada_image@2x'),
    Brand3: pngBaseV2('lv_image@2x'),
    Brand4: pngBaseV2('fendi_image@2x'),
    Brand5: pngBaseV2('hermes_image@2x'),
    Brand6: pngBaseV2('bv_image@2x'),
    Brand7: pngBaseV2('gucci_image@2x'),
    Brand8: pngBaseV2('dior_image@2x'),
    More: pngBaseV2('more_image@2x'),
    Service1: pngBaseV2('ticket_icon@2x'),
    Service2: pngBaseV2('bed_icon@2x'),
    Service3: pngBaseV2('position_icon@2x'),
    Service4: pngBaseV2('photo_icon@2x'),
    Service5: pngBaseV2('other_icon@2x'),
    ContactQR: pngBaseV2('follow_image@2x'),
    TeamQR: pngBaseV2('xiangx_image@2x'),
    DownloadQR: pngBaseV2('download_app_image@2x'),
    TeamIcon1: pngBaseV2('marketking_icon@2x'),
    TeamIcon2: pngBaseV2('hr_icon@2x'),
    TeamIcon3: pngBaseV2('message_icon@2x'),
    // ContactQR2: pngBaseV2("follow_image@2x_app"),

    TeamTitle: pngBase('team_bg_image@2x'),
    Identity: pngBase('identity_image@2x'),
    Team1: pngBase('team_one@2x'),
    Team1_1: pngBase('team_one_plant@2x'),
    Team2: pngBase('team_two@2x'),
    Team2_2: pngBase('team_two_before@2x'),
    Team3: pngBase('team_three@2x'),
    Team4: pngBase('team_four@2x')
};
